//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int Id { get; set; }
        public string Invoice_No { get; set; }
        public string Bill_By { get; set; }
        public string CompanyName { get; set; }
        public string Company_GSTNo { get; set; }
        public Nullable<decimal> TotalBillAmount { get; set; }
        public Nullable<decimal> GST_Paid { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
    }
}
