//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColorRate
    {
        public string ColorName { get; set; }
        public int ColorValue { get; set; }
        public Nullable<decimal> RatePerThousand { get; set; }
    }
}
