//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        public string Name { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> MobileNo { get; set; }
        public string GSTN_Number { get; set; }
        public string PanNo { get; set; }
        public string Registered { get; set; }
    }
}
