//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaulOffsetBill
    {
        public int Id { get; set; }
        public string Invoice_Number { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> RatePerThousand { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> PlateCharge { get; set; }
        public Nullable<decimal> GST_rate { get; set; }
        public Nullable<decimal> Total_Bill_Amount { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
    }
}
